config/routes.rb
Rails.application.routes.draw do
	resources :users do
		resources :phone_numbers, only: [:destroy, :create]
		resources :email_addresses, only: [:destroy, :create]
		resources :addresses, only: [:destroy, :create]

	end
	get '/phone_number/:label', to: 'phone_number#by_label', as: 'get_by_phone_type'
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
  validates :street, presence: true
  validates :zip_code, format: { with: /\d{5}/} ##todo: account for geographic segment
  validates :city, format: { with: /\w+/} 
  validates :state, format: { with: /[a-zA-Z]{2}/} #todo: validate against a full list of state codes
end

app/models/email_address.rb
class EmailAddress < ActiveRecord::Base
  belongs_to :user
  validates_uniqueness_of :user_id, :email_address
  validates :email_address, presence: true ##todo: create email format validation

  def self.is_valid_email?
  	self.email_address =~ /[a-zA-Z0-9]+\@[a-zA-Z]+\.[a-zA-Z]{2}/
  end

end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
  belongs_to :user
  validates :area_code, format: { with: /\d{3}/} #todo: account for international area codes?
  validates :phone_number, format: { with: /\d{7}/} ##todo: account for international #s?
  validates :label, format: { with: /(none|home|work|mobile)/}
end

app/models/phone_numbers.rb
class PhoneNumbers < ActiveRecord::Base
  belongs_to :user
  validates :area_code, format: { with: /\d{3}/} #todo: account for international area codes?
  validates :phone_number, format: { with: /\d{7}/} ##todo: account for international #s?
  validates :label, format: { with: /(none|home|work|mobile)/}

  scope :by_label, -> (label) { where(label: label) unless label.blank? }

end

app/models/user.rb
class User < ActiveRecord::Base
	validates :first_name, presence: true
	validates :last_name, presence: true
	
	has_many :email_addresses
	has_many :phone_numbers
	has_many :addresses
	#clean up
	after_destroy { |record| 
		PhoneNumbers.delete(user_id: record.id)
		EmailAddress.delete(user_id: record.id)
		Address.delete(user_id: record.id)
	}


end

app/controllers/address_controller.rb
class AddressController < ApplicationController
	def destroy
		render json: {
			status: Address.delete(params[:id])
		}
	end
	def create
		begin
			status = Address.new(address_params).save!
			msg = ""
		rescue Exception => e
			msg = e.message
		end
		render json: {
			status: status.to_s,
			message: msg
		}
	end
	private
	def address_params
		params.permit(:street, :state, :city, :zip_code, :user_id)
	end

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
	def destroy
		render json: {
			status: Address.delete(params[:id])
		}
	end
	def create
		begin
			status = Address.new(address_params).save!
			msg = ""
		rescue Exception => e
			msg = e.message
		end
		render json: {
			status: status.to_s,
			message: msg
		}
	end
	private
	def address_params
		params.permit(:street, :state, :city, :zip_code, :user_id)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/email_address_controller.rb
class EmailAddressController < ApplicationController
	def destroy
		render json: {
			status: EmailAddress.delete(params[:id])
		}
	end
	def create
		begin
			status = EmailAddress.new(email_address_params).save!
			msg = ""
		rescue Exception => e
			msg = e.message
		end
		render json: {
			status: status.to_s,
			message: msg
		}
	end
	private
	def email_address_params
		params.permit(:email_address, :user_id)
	end

end

app/controllers/email_addresses_controller.rb
class EmailAddressesController < ApplicationController
	def destroy
		render json: {
			status: EmailAddress.delete(params[:id])
		}
	end
	def create
		begin
			status = EmailAddress.new(email_address_params).save!
			msg = ""
		rescue Exception => e
			msg = e.message
		end
		render json: {
			status: status.to_s,
			message: msg
		}
	end
	private
	def email_address_params
		params.permit(:email_address, :user_id)
	end

end

app/controllers/phone_number_controller.rb
class PhoneNumberController < ApplicationController
	def destroy
		render json: {
			status: PhoneNumbers.delete(params[:id])
		}
	end
	def create
		begin
			status = PhoneNumbers.new(phone_number_params).save!
			msg = ""
		rescue Exception => e
			msg = e.message
		end
		render json: {
			status: status.to_s,
			message: msg
		}
	end

	def by_label
		@numbers = PhoneNumbers.by_label params[:label]
		render 'by_label'
	end


	private
	def phone_number_params
		params.permit(:area_code, :phone_number, :label, :user_id)
	end


end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
	def destroy
		render json: {
			status: PhoneNumbers.delete(params[:id])
		}
	end
	def create
		begin
			status = PhoneNumbers.new(phone_number_params).save!
			msg = ""
		rescue Exception => e
			msg = e.message
		end
		render json: {
			status: status.to_s,
			message: msg
		}
	end

	def by_label
		@numbers = PhoneNumbers.where(params.permit(:label))
		render 'by_label'
	end


	private
	def phone_number_params
		params.permit(:area_code, :phone_number, :label, :user_id)
	end


end

app/controllers/user_controller.rb
class UserController < ApplicationController
protect_from_forgery :except => :create 
	def index
		@users = User.all
	end

	def new
		@csrf_token = form_authenticity_token
	end

	def create
		begin
			new_user = User.new(user_params)
			User.transaction do
				new_user.save!
				if !params[:email_address].blank?
					params[:email_addresses].each { |email_address|
						new_user.email_address.create!(email_address.permit(:email_address))
					}
				end
				if !params[:phone_numbers].blank?
					params[:phone_numbers].each { |phone_number|
						new_user.phone_numbers.create!(phone_number.permit(:area_code, :phone_number))
					}
				end
				if !params[:addresses].blank?
					params[:addresses].each {|address|
						new_user.address.create!(address.permit(:street, :city, :state, :zip_code))
					}
				end
			end
		rescue Exception => e
			@error = e.message
			render 'new'
			return
		end
		redirect_to new_user
	end

	def edit
		show
		render 'edit'
	end



	def show
		@user = User.where(params.permit(:id)).includes(:addresses, :phone_numbers, :email_addresses).first
		redirect_to user_index_url if !@user
	end

	def destroy
		User.delete(params[:id])
		redirect_to user_index_url
	end

	private
	def user_params
		params.require(:user).permit(:first_name, :last_name)
	end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
protect_from_forgery :except => :create 
	def index
		@users = User.all
	end

	def new
	end

	def create
		begin
			new_user = User.new(user_params)
			User.transaction do
				new_user.save!
				if !params[:email_address].blank?
					params[:email_addresses].each { |email_address|
						new_user.email_address.create!(email_address.permit(:email_address))
					}
				end
				if !params[:phone_numbers].blank?
					params[:phone_numbers].each { |phone_number|
						new_user.phone_numbers.create!(phone_number.permit(:area_code, :phone_number))
					}
				end
				if !params[:addresses].blank?
					params[:addresses].each {|address|
						new_user.address.create!(address.permit(:street, :city, :state, :zip_code))
					}
				end
			end
		rescue Exception => e
			@error = e.message
			render 'new'
			return
		end
		redirect_to new_user
	end

	def edit
		show
		render 'edit'
	end



	def show
		@user = User.where(params.permit(:id)).includes(:addresses, :phone_numbers, :email_addresses).first
		redirect_to user_index_url if !@user
	end

	def destroy
		User.delete(params[:id])
		redirect_to user_index_url
	end

	private
	def user_params
		params.require(:user).permit(:first_name, :last_name)
	end



end

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html{lang: "en"}
  %title KL Address Book
  =stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true

  =javascript_include_tag 'application', 'data-turbolinks-track' => true
  =csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      %a.navbar-brand{href: "/"} Home
    %div.container
      =yield

app/views/phone_numbers/by_label.html.haml
%table.users{ border:  1, width:  "100%", class:  @numbers.blank? && "empty"}
	%thead
		%tr
			%th= "User Id"
			%th= "Area Code"
			%th= "Phone Number"
			%th= "Label"
	%tbody
		- @numbers.each do|number|
			%tr.number
				%td
					%a{href:  "/user/"+number.user_id.to_s}= number.user_id.to_s
				%td= number.area_code
				%td= number.phone_number
				%td= number.label

app/views/user/edit.html.haml
%h1= @user.first_name+" "+@user.last_name
%h2= "Addresses"
%table.addresses{ border: 1, width: "100%"}
	%thead
		%tr
			%th= "Street"
			%th= "City"
			%th= "State"
			%th= "Zip Code"
			%th= "Action"
	%tbody
		- @addresses.each do|address|
			%tr.address{ data: {user_id: @user.id}}
				%td= address.street
				%td= address.city
				%td= address.state
				%td= address.zip_code
				%td
					%a.delete{href: "#", :data=>{type: "address", id: address.id}}= "x"
		%tr.edit_fields{data: {type: "address", user_id: @user.id}}
			%td
				%input.street{placeholder:  "Street"}
			%td 
				%input.city{placeholder:  "City"}
			%td
				%input.state{placeholder:  "State"}
			%td
				%input.zip_code{placeholder:  "Zip Code"}
			%td
				%a.edit{href: "#", type: "Submit", value:  "Add"}= "Add"

%h2= "Phone Numbers"
%table.phone_numbers{ border:  1, width:  "100%", class: @phone_numbers.blank? && "empty"}
	%thead
		%tr
			%th= "Area Code"
			%th= "Phone Number"
			%th= "Label"
			%th= "Action"
	%tbody
		- @phone_numbers.each do|phone_number|
			%tr.phone_number{ data: {user_id: @user.id}}
				%td= phone_number.area_code
				%td= phone_number.phone_number
				%td= phone_number.label
				%td
					%a.delete{href: "#", :data=>{type: "phone_number", id: phone_number.id}}= "x"
		%tr.edit_fields{data: {type: "phone_number", user_id: @user.id}}
			%td
				%input.area_code{placeholder:  "Area Code"}
			%td
				%input.phone_number{placeholder:  "Phone Number"}
			%td
				%select.label
				-# TODO: switch from using hardcoded values in future
					%option{value:  "none"}= "None"
					%option{value:  "home"}= "Home"
					%option{value:  "work"}= "Work"
					%option{value:  "mobile"}= "Mobile"
			%td
				%a.edit{href: "#", type: "Submit", value:  "Add"}= "Add"

%h2= "Email Addresses"
%table.email_addresses{ border:  1, width:  "100%", class: @email_addresses.blank? && "empty"}
	%thead
		%tr
			%th= "Email Address"
			%th= "Action"
	%tbody
		- @email_addresses.each do|email_address|
			%tr.email_address{ data: {user_id: @user.id}}
				%td= email_address.email_address
				%td
					%a.delete{href: "#", :data=>{type: "email_address", id: email_address.id}}= "x"
		%tr.edit_fields{data: {type: "email_address", user_id: @user.id}}
			%td
				%input.email_address{placeholder:  "Email"}
			%td
				%a.edit{href: "#", type: "Submit", value:  "Add"}= "Add"

= link_to "Back", user_index_url, title:  'Back'

= link_to "Delete User", @user, method: :delete

app/views/user/show.html.haml
%h1= @user.first_name+" "+@user.last_name
%h2= "Addresses"
%table.addresses{ border:  1, width:  "100%", class:  @addresses.blank? && "empty"}
	%thead
		%tr
			%th= "Street"
			%th= "City"
			%th= "State"
			%th= "Zip Code"
	%tbody
		- @addresses.each do|address|
			%tr.address
				%td= address.street
				%td= address.city
				%td= address.state
				%td= address.zip_code

%h2= "Phone Numbers"
%table.phone_numbers{ border:  1, width:  "100%", class:  @phone_numbers.blank? && "empty"}
	%thead
		%tr
			%th= "Area Code"
			%th= "Phone Number"
			%th= "Label"
	%tbody
		- @phone_numbers.each do|phone_number|
			%tr.phone_number
				%td= phone_number.area_code
				%td= phone_number.phone_number
				%td= phone_number.label

%h2= "Email Addresses"
%table.email_addresses{ border:  1, width:  "100%", class:  @email_addresses.blank? && "empty"}
	%thead
		%tr
			%th= "Email Address"
	%tbody
		- @email_addresses.each do|email_address|
			%tr.email_address
				%td= email_address.email_address

= link_to "Back", user_index_url, title:  'Back'
= link_to "Edit", edit_user_url, title:  "Edit"
= link_to "Delete", @user, method: :delete

app/views/users/edit.html.haml
%h1= @user.first_name+" "+@user.last_name
%h2 Addresses
%table.addresses{ border: 1, width: "100%"}
	%thead
		%tr
			%th Street
			%th City
			%th State
			%th Zip Code
			%th Action
	%tbody
		- @user.addresses.each do|address|
			%tr.address{ data: {user_id: @user.id}}
				%td= address.street
				%td= address.city
				%td= address.state
				%td= address.zip_code
				%td
					%a.delete{href: "#", :data=>{type: "address", id: address.id}} x
		%tr.edit_fields{data: {type: "address", user_id: @user.id}}
			%td
				%input.street{placeholder:  "Street"}
			%td 
				%input.city{placeholder:  "City"}
			%td
				%input.state{placeholder:  "State"}
			%td
				%input.zip_code{placeholder:  "Zip Code"}
			%td
				%a.edit{href: "#", type: "Submit", value:  "Add"} "Add"

%h2 Phone Numbers
%table.phone_numbers{ border:  1, width:  "100%", class: @user.phone_numbers.blank? && "empty"}
	%thead
		%tr
			%th Area Code
			%th Phone Number
			%th Label
			%th Action
	%tbody
		- @user.phone_numbers.each do|phone_number|
			%tr.phone_number{ data: {user_id: @user.id}}
				%td= phone_number.area_code
				%td= phone_number.phone_number
				%td= phone_number.label
				%td
					%a.delete{href: "#", :data=>{type: "phone_number", id: phone_number.id}} x
		%tr.edit_fields{data: {type: "phone_number", user_id: @user.id}}
			%td
				%input.area_code{placeholder:  "Area Code"}
			%td
				%input.phone_number{placeholder:  "Phone Number"}
			%td
				%select.label
				-# TODO: switch from using hardcoded values in future
					%option{value:  "none"} None
					%option{value:  "home"} Home
					%option{value:  "work"} Work
					%option{value:  "mobile"} Mobile
			%td
				%a.edit{href: "#", type: "Submit", value:  "Add"}= "Add"

%h2 Email Addresses
%table.email_addresses{ border:  1, width:  "100%", class: @user.email_addresses.blank? && "empty"}
	%thead
		%tr
			%th Email Address
			%th Action
	%tbody
		- @user.email_addresses.each do|email_address|
			%tr.email_address{ data: {user_id: @user.id}}
				%td= email_address.email_address
				%td
					%a.delete{href: "#", :data=>{type: "email_address", id: email_address.id}} x
		%tr.edit_fields{data: {type: "email_address", user_id: @user.id}}
			%td
				%input.email_address{placeholder:  "Email"}
			%td
				%a.edit{href: "#", type: "Submit", value:  "Add"}= "Add"

= link_to "Back", user_url, title:  'Back'

= link_to "Delete User", @user, method: :delete

app/views/users/index.html.haml
%table.table.table-bordered.users{ border:  1, width:  "100%", class:  @users.blank? && "empty"}
	%thead
		%tr
			%th Id
			%th First Name
			%th Last Name
			%th Last Updated
			%th Delete
	%tbody
		- @users.each do|user|
			%tr.user{ data: { user_id:  user.id}}
				%td= link_to user.id, user
				%td= user.first_name
				%td= user.last_name
				%td= user.updated_at.strftime("%m-%d-%Y %I:%M %p")
				%td= link_to "Delete", user, method: :delete, class: "btn btn-danger"

=link_to "Add New User", new_user_path, title:  'Add New User', class: "btn btn-primary"				

app/views/users/new.html.haml
%h1= "Add New User"

%form.new_user_form{ action:  "/user", method:  "post"}
	%input{ type:  "hidden", name:  "authenticity_token", value: request_forgery_protection_token}
	%div.form-group
		%label First Name *
		%input.form-control{ type:  "text", name:  "user[first_name]", placeholder:  "First Name", required:  true}
	%div.form-group
		%label Last Name *
		%input.form-control{ type:  "text", name:  "user[last_name]", placeholder:  "Last Name", required:  true}

	%fieldset
		%legend Address(es)
		%a.add{href:  "#", data:  {template:  "address_template"}} Add Address


	%fieldset
		%legend Phone Number(s)
		%a.add{href:  "#", data:  {template:  "phone_number_template"}} Add Phone Number

	%fieldset
		%legend Email Address(es)
		%a.add{href:  "#", data: {template:  "email_address_template"}} Add Email Address

	%input.btn.btn-primary{ type:  "submit", value:  "Submit"}


%script{ type: "type/html", id: "address_template"}
	%div.form-group
		%input.form-control{ type:  "text", name:  "addresses[][street]", placeholder:  "Street"}
		%input.form-control{ type:  "text", name:  "addresses[][city]", placeholder:  "City"}
		%input.form-control{ type:  "text", name:  "addresses[][state]", placeholder:  "State", pattern:  "[A-Za-z]{2}"}
		%input.form-control{ type:  "text", name:  "addresses[][zip_code]", placeholder:  "Zip Code", pattern:  "\\d{5}"}
		%a.close{href:  "#"} x
		%hr

%script{ type: "type/html",  id: "phone_number_template"}
	%div.form-group
		%input.form-control{ type:  "text", name:  "phone_numbers[][area_code]", placeholder:  "Area Code", pattern:  "\\d{3}"}
		%input.form-control{ type:  "text", name:  "phone_numbers[][phone_number]", placeholder:  "Phone Number", pattern:  "\\d{7}"}
		%a.close{href:  "#"} x
		%hr

%script{ type: "type/html",  id: "email_address_template"}
	%div.form-group
		%input.form-control{ type:  "email", name:  "email_addresses[][email_address]", placeholder:  "Email Address" }
		%a.close{href:  "#"} x
		%hr


=link_to "Back", users_url, class: "btn btn-primary"

app/views/users/show.html.haml
%h2= @user.first_name+" "+@user.last_name
%h3 Address(es)
%table.table.table-bordered.addresses
	%thead
		%tr
			%th Street
			%th City
			%th State
			%th Zip Code
	%tbody
		- @user.addresses.each do|address|
			%tr.address
				%td= address.street
				%td= address.city
				%td= address.state
				%td= address.zip_code

%h3 Phone Number(s)
%table.table.table-bordered.phone_numbers
	%thead
		%tr
			%th Area Code
			%th Phone Number
			%th Label
	%tbody
		- @user.phone_numbers.each do|phone_number|
			%tr.phone_number
				%td= phone_number.area_code
				%td= phone_number.phone_number
				%td= phone_number.label

%h3 Email Address(es)
%table.table.table-bordered.email_addresses
	%thead
		%tr
			%th Email Address
	%tbody
		- @user.email_addresses.each do|email_address|
			%tr.email_address
				%td= email_address.email_address

= link_to "Back", user_url, title:  'Back', class: "btn btn-primary"
= link_to "Edit", edit_user_url, title:  "Edit", class: "btn btn-warning"
= link_to "Delete", @user, method: :delete, class: "btn btn-danger"